version: "3.7"

volumes:
  node_modules:

services:
  redis_single_instance:
    image: redis

  # redis_single_cluster_1:
  #   image: redis

  # redis_single_cluster_2:
  #   image: redis

  # redis_multi_instance_a:
  #   image: redis
  # redis_multi_instance_b:
  #   image: redis
  # redis_multi_instance_c:
  #   image: redis

  # redis_multi_cluster_a_1:
  #   image: redis
  # redis_multi_cluster_a_2:
  #   image: redis

  # redis_multi_cluster_b_1:
  #   image: redis
  # redis_multi_cluster_b_2:
  #   image: redis

  # redis_multi_cluster_c_1:
  #   image: redis
  # redis_multi_cluster_c_2:
  #   image: redis

  redlock:
    image: node:14
    command: yarn build:development
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /build
      - type: volume
        source: node_modules
        target: /build/node_modules
