version: "3.7"

volumes:
  node_modules:

services:
  redis_single_instance:
    image: redis

  redis_multi_instance_a:
    image: redis
  redis_multi_instance_b:
    image: redis
  redis_multi_instance_c:
    image: redis

  # redis_single_cluster_1:
  #   image: redis

  # redis_single_cluster_2:
  #   image: redis

  # redis_multi_cluster_a_1:
  #   image: redis
  # redis_multi_cluster_a_2:
  #   image: redis

  # redis_multi_cluster_b_1:
  #   image: redis
  # redis_multi_cluster_b_2:
  #   image: redis

  # redis_multi_cluster_c_1:
  #   image: redis
  # redis_multi_cluster_c_2:
  #   image: redis

  # This container installs node modules into the node_modules volume.
  installer:
    image: node:16
    working_dir: /workspace
    command: yarn
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: node_modules
        target: /workspace/node_modules

  # This container watches for changes and builds the application.
  builder:
    depends_on:
      - installer
    image: node:16
    working_dir: /workspace
    command: ./scripts/await.sh node_modules/.bin/tsc yarn build:development
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: node_modules
        target: /workspace/node_modules

  # This container runs the tests.
  tester:
    depends_on:
      - builder
      - redis_single_instance
    image: node:16
    working_dir: /workspace
    command: ./scripts/await.sh node_modules/.bin/ava ./scripts/await.sh dist/redlock.js yarn test:development
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: node_modules
        target: /workspace/node_modules
