name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test with Node.js v${{ matrix.node }} and ${{ matrix.os }}
    runs-on: "ubuntu-latest"
    container: "node:${{matrix.node}}"
    strategy:
      matrix:
        node: ["12", "14", "16"]
    services:
      redis-single-instance:
        image: redis
      redis-multi-instance-a:
        image: redis
      redis-multi-instance-b:
        image: redis
      redis-multi-instance-c:
        image: redis
    steps:
      - uses: actions/checkout@v2
      - name: Install dependancies
        run: yarn install --frozen-lockfile
      - name: Lint the source
        run: yarn lint
      - name: Transpile into dist
        run: yarn build
      - name: Run tests
        run: yarn test
